version: '3.9'
services:
  emqx-cluster-1: # emqx node-1
    image: emqx:5.5.0
    container_name: 'emqx-cluster-1-container'
    hostname: 'emqx1-cluster.emqx.io'
    healthcheck: # health check endpoint
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks: # network configuration
      emqx-bridge:
        aliases:
          - node1.emqx.io
    environment:
      - "EMQX_NODE_NAME=emqx@emqx1-cluster.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx1-cluster.emqx.io,emqx@emqx2-cluster.emqx.io,emqx@emqx3-cluster.emqx.io]"

  emqx-cluster-2: # emqx node-2
    image: emqx:5.5.0
    container_name: 'emqx-cluster-2-container'
    hostname: 'emqx2-cluster.emqx.io'
    healthcheck: # health check endpoint
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    networks: # network configuration
      emqx-bridge:
        aliases:
          - node2.emqx.io
    environment:
      - "EMQX_NODE_NAME=emqx@emqx2-cluster.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx1-cluster.emqx.io,emqx@emqx2-cluster.emqx.io,emqx@emqx3-cluster.emqx.io]"

  emqx-cluster-3: # emqx node-2
    image: emqx:5.5.0
    container_name: 'emqx-cluster-3-container'
    hostname: 'emqx3-cluster.emqx.io'
    healthcheck: # health check endpoint
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    networks: # network configuration
      emqx-bridge:
        aliases:
          - node3.emqx.io
    environment:
      - "EMQX_NODE_NAME=emqx@emqx3-cluster.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx1-cluster.emqx.io,emqx@emqx2-cluster.emqx.io,emqx@emqx3-cluster.emqx.io]"

  nginx: # nginx load-balancer
    image: nginx
    container_name: nginx-container
    hostname: nginx-container
    ports:
      - "1883:1883"
      - "8888:8888" # nginx status
      - "80:80"
    volumes: # nginx config file mounting
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - emqx-cluster-1
      - emqx-cluster-2
      - emqx-cluster-3
    networks:
      emqx-bridge:
        aliases:
          - lb.nginx

  emqx-client: # a client for testing the emqx cluster
    container_name: "emqx-client-container"
    hostname: "emqx-client-container"
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - "C_TOPIC=rides"
      - "C_MESSAGE=new-ride"
      - "C_INTERVAL=100"
      - "EMQX_HOST=lb.nginx"
      - "EMQX_PROTOCOL=tcp"
      - "EMQX_PORT=1883"
      - "EMQX_CLIENT_ID=ridesconsumer"
      - "EMQX_KEEP_ALIVE=5"
      - "EMQX_PING_TIMEOUT=5"
    networks:
      - emqx-bridge

# network config
networks:
  emqx-bridge:
    driver: emqx-net
